apiVersion: v1
kind: Service
metadata:
  name: front-end
  labels:
    app: online-store
  annotations:
    "consul.hashicorp.com/service-name": "front-end"
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: online-store
